### ISSUE TITLE
运行出现的问题

### ISSUE THREAD

**Issue by jinzhi666** [woolen-sheep/md2report#4]
# 第一次提示缺少输出 output.docx 文件

```txt
D:\university\master\courses\md2report\backend>python md2report.py -i test/test_case/5.2数据结构实验报告.md
Please give me star if this application helps you!
如果这个应用有帮助到你，请给我点一个 star！
https://github.com/woolen-sheep/md2report
Traceback (most recent call last):
  File "D:\university\master\courses\md2report\backend\filters\general.py", line 211, in <module>
    pf.toJSONFilter(process_report)
  File "D:\software\Anaconda3\lib\site-packages\panflute\io.py", line 148, in toJSONFilter
    return run_filter(*args, **kwargs)
  File "D:\software\Anaconda3\lib\site-packages\panflute\io.py", line 227, in run_filter
    return run_filters([action], *args, **kwargs)
  File "D:\software\Anaconda3\lib\site-packages\panflute\io.py", line 200, in run_filters
    doc = load(input_stream=input_stream)
  File "D:\software\Anaconda3\lib\site-packages\panflute\io.py", line 58, in load
    doc = json.load(input_stream, object_hook=from_json)
  File "D:\software\Anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\software\Anaconda3\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "D:\software\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\software\Anaconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "D:\software\Anaconda3\lib\site-packages\panflute\elements.py", line 1384, in from_json
    raise NotImplementedError(f'Unknown tag: {tag}')
NotImplementedError: Unknown tag: Caption
Error running filter D:\university\master\courses\md2report\backend\filters\general.py:
Filter returned error status 1
Traceback (most recent call last):
  File "md2report.py", line 141, in <module>
    convert_md_to_docx(conf)
  File "md2report.py", line 91, in convert_md_to_docx
    handler_map[handler_name](str(output_path.absolute()), **params)
  File "D:\university\master\courses\md2report\backend\docx_handler\hust.py", line 102, in process_hust_docx
    doc: TDocument = Document(filename)
  File "D:\software\Anaconda3\lib\site-packages\docx\api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "D:\software\Anaconda3\lib\site-packages\docx\opc\package.py", line 128, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "D:\software\Anaconda3\lib\site-packages\docx\opc\pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "D:\software\Anaconda3\lib\site-packages\docx\opc\phys_pkg.py", line 30, in __new__
    raise PackageNotFoundError(
docx.opc.exceptions.PackageNotFoundError: Package not found at 'D:\university\master\courses\md2report\backend\output.docx'
```

# 补上 output.docx 后提示如下

```txt
D:\university\master\courses\md2report\backend>python md2report.py -i test/test_case/5.2数据结构实验报告.md
Please give me star if this application helps you!
如果这个应用有帮助到你，请给我点一个 star！
https://github.com/woolen-sheep/md2report
Traceback (most recent call last):
  File "D:\university\master\courses\md2report\backend\filters\general.py", line 211, in <module>
    pf.toJSONFilter(process_report)
  File "D:\software\Anaconda3\lib\site-packages\panflute\io.py", line 148, in toJSONFilter
    return run_filter(*args, **kwargs)
  File "D:\software\Anaconda3\lib\site-packages\panflute\io.py", line 227, in run_filter
    return run_filters([action], *args, **kwargs)
  File "D:\software\Anaconda3\lib\site-packages\panflute\io.py", line 200, in run_filters
    doc = load(input_stream=input_stream)
  File "D:\software\Anaconda3\lib\site-packages\panflute\io.py", line 58, in load
    doc = json.load(input_stream, object_hook=from_json)
  File "D:\software\Anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\software\Anaconda3\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "D:\software\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\software\Anaconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "D:\software\Anaconda3\lib\site-packages\panflute\elements.py", line 1384, in from_json
    raise NotImplementedError(f'Unknown tag: {tag}')
NotImplementedError: Unknown tag: Caption
Error running filter D:\university\master\courses\md2report\backend\filters\general.py:
Filter returned error status 1
```

应该是 --filter 过滤器这个general.py python文件有问题吧？
pandoc 输出的参数是 

```bash
pandoc -s --toc D:\university\master\courses\md2report\backend\test\test_case\5.2数据结构实验报告.md.validated.md --reference-doc D:\university\master\courses\md2report\backend\reference-docs\HUST.docx --filter D:\university\master\courses\md2report\backend\filters\general.py -o D:\university\master\courses\md2report\backend\output.docx
```

去掉 --filter 参数就可以用，但是缺少了添加摘要、修改图片格式等操作

**Comment by woolen-sheep** [comment]
你提供的第一个日志中：
```
Filter returned error status 1
```
说明filter已经被调用了，但是出错了，因此没能成功生成docx文件。
docx未找到的错误是python-docx报的，与pandoc无关。
尚未在windows下测试过，之后我会试一下。

**Comment by jinzhi666** [comment]
已经解决，是 pandoc 版本的问题，panflute 不支持 pandoc 2.10，更换 2.11以上就可以用了。参考 「[panflute 说明](https://github.com/sergiocorreia/panflute)」

**Comment by woolen-sheep** [comment]
之后我会把这个加进README
