### ISSUE TITLE
转换测试用例时报错：pandoc: Data.Binary.Get.runGet at position 4: Did not find end of central directory signature

### ISSUE THREAD

**Issue by jyi2ya** [woolen-sheep/md2report#9]
运行的命令：

```sh
git pull
cd backend
poetry install
poetry shell
python md2report.py -i test/test_case/5.2数据结构实验报告.md
```

完整的错误信息：

```plain
(md2report-py3.10) [1] 03:37 Syameimaru-Aya (master) ~/sr/hu/md2report/backend
0 python md2report.py -i test/test_case/5.2数据结构实验报告.md
Please give me star if this application helps you!
如果这个应用有帮助到你，请给我点一个 star！
https://github.com/woolen-sheep/md2report
pandoc: Data.Binary.Get.runGet at position 4: Did not find end of central directory signature
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.8.0:Data.Binary.Get
Traceback (most recent call last):
  File "/home/jyi/src/hust/md2report/backend/md2report.py", line 141, in <module>
    convert_md_to_docx(conf)
  File "/home/jyi/src/hust/md2report/backend/md2report.py", line 91, in convert_md_to_docx
    handler_map[handler_name](str(output_path.absolute()), **params)
  File "/home/jyi/src/hust/md2report/backend/docx_handler/hust.py", line 102, in process_hust_docx
    doc: TDocument = Document(filename)
  File "/home/jyi/.cache/pypoetry/virtualenvs/md2report-5grrADQi-py3.10/lib/python3.10/site-packages/docx/api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "/home/jyi/.cache/pypoetry/virtualenvs/md2report-5grrADQi-py3.10/lib/python3.10/site-packages/docx/opc/package.py", line 128, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/home/jyi/.cache/pypoetry/virtualenvs/md2report-5grrADQi-py3.10/lib/python3.10/site-packages/docx/opc/pkgreader.py", line 32, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/home/jyi/.cache/pypoetry/virtualenvs/md2report-5grrADQi-py3.10/lib/python3.10/site-packages/docx/opc/phys_pkg.py", line 30, in __new__
    raise PackageNotFoundError(
docx.opc.exceptions.PackageNotFoundError: Package not found at '/home/jyi/src/hust/md2report/backend/output.docx'
```

各个程序的版本：

+ python: 3.10.9
+ pandoc: 2.17.1.1
+ poetry: 1.2.2

```plain
(md2report-py3.10) 03:46 Syameimaru-Aya (master) ~/sr/hu/md2report/backend
0 python --version
Python 3.10.9
(md2report-py3.10) 03:46 Syameimaru-Aya (master) ~/sr/hu/md2report/backend
0 pandoc --version
pandoc 2.17.1.1
Compiled with pandoc-types 1.22.2.1, texmath 0.12.4, skylighting 0.12.3.1,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /home/jyi/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
(md2report-py3.10) 03:46 Syameimaru-Aya (master) ~/sr/hu/md2report/backend
0 poetry --version
Poetry (version 1.2.2)
```

发行版：`Debian GNU/Linux bookworm/sid`

**Comment by woolen-sheep** [comment]
参考readme，安装git lfs。

**Comment by jyi2ya** [comment]
> 参考readme，安装git lfs。

谢谢，问题解决了。
